spring:
  application:
    name: ga-storybook

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # auto-creates tables from entities (use 'validate' in prod)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: simple   # in-memory caching for audio

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  bucket: ${SUPABASE_BUCKET}

flask:
  tts:
    url: ${FLASK_TTS_URL}

server:
  port: ${PORT:8080}   # default 8080 if PORT not set

logging:
  level:
    root: INFO
    gh.duadeketet3n.storybook: DEBUG

tts:
  mode: test